name: mvvm_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  # firebase_auth: ^3.3.11
  # cloud_firestore: ^3.1.10
  # firebase_storage: ^10.2.9
  # firebase_core: ^1.13.1
  # firebase_messaging: ^11.2.11

  json_serializable: ^6.1.5
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1
  
  shared_preferences: ^2.0.13
  flutter_local_notifications: ^9.4.0
  
  image_picker: ^0.8.4+11
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  carousel_slider: ^4.0.0
  table_calendar: ^3.0.5
  date_time_picker: ^2.1.0
  youtube_player_flutter: ^8.0.0
  flutter_form_builder: ^7.1.1
  intl: ^0.17.0

  get_it: ^7.2.0
  rxdart: ^0.27.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  freezed: ^1.1.1
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  #generate: true

  assets:
     - assets/images/onboarding_logo1.svg
     - assets/images/onboarding_logo2.svg
     - assets/images/onboarding_logo3.svg
     - assets/images/onboarding_logo4.svg
     - assets/images/hollow_cirlce_ic.svg
     - assets/images/left_arrow_ic.svg
     - assets/images/right_arrow_ic.svg
     - assets/images/solid_circle_ic.svg
     - assets/images/photo_camera_ic.svg
     - assets/images/settings_right_arrow_ic.svg
     - assets/images/change_lang_ic.svg
     - assets/images/contact_us_ic.svg
     - assets/images/invite_friends_ic.svg
     - assets/images/logout_ic.svg
     - assets/images/calendar.svg
     - assets/json/loading.json
     - assets/json/error.json
     - assets/json/empty.json
     - assets/json/success.json
     - assets/json/farming_splash.json
    
  fonts:
     - family: ABeeZee
     - fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
          weight: 400
        - asset: assets/fonts/ABeeZee-Italic.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"