class AppStrings {
  static const String noRouteFound = 'no_route_found';
  static const String registerText = 'register_text';
  static const String loading = 'loading';
  static const String retryAgain = 'Try again';
  static const String ok = 'ok';
  static const String emailHint = 'email_hint';
  static const String invalidEmail = 'invalid_email';
  static const String resetPassword = 'reset_password';
  static const String success = 'success';
  static const String profilePicture = 'upload_profile_picture';
  static const String photoGalley = 'photo_gallery';
  static const String photoCamera = 'camera';
  static const String register = 'register';
  static const String haveAccount = 'already_have_account';
  static const String home = 'Calendar';
  static const String chat = 'Chat';
  static const String feed = 'Tutorials';
  static const String departments = 'Departments';
  static const String programs = 'Programs';
  static const String search = 'Search';
  static const String settings = 'Settings';
  static const String services = 'services';
  static const String stores = 'stores';
  static const String details = 'details';
  static const String about = 'about';
  static const String logout = 'logout';
  static const String content = 'Content';
  static const String empty = 'Empty';
  static const String error = 'Error';
  static const String isaAgri = 'ISAGRI';
  static const String audit = 'Finance';
  static const String tips = 'Tips';
  static const String save = 'Save';

  // error handler
  static const String badRequestError = 'bad_request_error';
  static const String noContent = 'no_content';
  static const String forbiddenError = 'forbidden_error';
  static const String unauthorizedError = 'unauthorized_error';
  static const String notFoundError = 'not_found_error';
  static const String conflictError = 'conflict_error';
  static const String internalServerError = 'internal_server_error';
  static const String unknownError = 'unknown_error';
  static const String timeoutError = 'timeout_error';
  static const String defaultError = 'default_error';
  static const String cacheError = 'cache_error';
  static const String noInternetError = 'no_internet_error';
}
